### ISSUE TITLE
run.sh - No such file or directory

### ISSUE THREAD

**Issue by warlordattack** [Yummiii/sd-webui-forge-docker#7]
Hello i try to run this in WSL ubuntu docker,

I have this issue : 
```
2024-09-14T13:03:47.159124182Z Starting Stable Diffusion WebUI
2024-09-14T13:03:47.161881362Z Files found, starting...
2024-09-14T13:03:47.163535048Z fatal: not a git repository (or any parent up to mount point /app)
2024-09-14T13:03:47.163545560Z Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2024-09-14T13:03:47.164154418Z /app/run.sh: line 32: /app/sd-webui/webui.sh: No such file or directory
```

My Compose file : 
```
version: "3.9"
services:
  srv_sdwf:
    container_name: ${C_SDWF}
    hostname: ${C_SDWF_HOST}
    image: ${C_SDWF_IMG}    
    restart: ${C_ALL_RESTART_NO}
    ports:
      - ${C_SDWF_7860}:7860
    volumes:
      - ${REP_APPDATA}/${C_SDWF}:/app/sd-webui
    environment:
      - "ARGS=--listen --enable-insecure-extension-access" # Insecure extension access is required if you want to install extensions with the listen flag
      - "UI=forge" # forge, auto : forge webui, AUTOMATIC1111 webui
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_LABEL_ENABLE}"
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      web:
        ipv4_address: ${C_SDWF_IP_WEB}
networks: 
  web: 
    external: true
```
In appdata folder i only see venv dir created.

Help please :)

If i delete and recreate container i have this log : 

[ai-sdwf-2024-09-14T13-11-24.log](https://github.com/user-attachments/files/17002527/ai-sdwf-2024-09-14T13-11-24.log)
